version: '3'

volumes:
  mysqldata:

services:
  app:
    # 起動するイメージを指定（ここではNode.js v12の公式イメージ）
    image: node:12
    # 環境変数を設定
    env_file:
      - .env
    tty: true
    # ホスト側のポート:コンテナのポート
    ports:
      - '3000:3000'
    # ソースコードを格納するフォルダをマウント
    #（ホスト側の./srcをコンテナの/appにマウント）
    volumes:
      - ./:/app
    # 起動時のカレントフォルダを指定
    working_dir: /app
    # 起動後に実行するコマンドを指定
    command: node app.js

    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    env_file: ./mysql/mysql.env
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./MYSQL_DATA:/home/
      - ./mysql/conf:/etc/mysql/conf.d/:ro
      - mysqldata:/var/lib/mysql
